apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: react-s3-website-template
  title: React S3 Website
  description: Creates a new static React website deployed via Terraform and GitHub Actions.
spec:
  owner: platform-team
  type: website

  parameters:
    - title: Provide Component Information
      required:
        - component_id
        - repoUrl
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component (e.g., my-awesome-app).
        description:
          title: Description
          type: string
          description: A brief description of the website.
        repoUrl:
          title: GitHub Repository
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: register
      name: Register Component in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: View in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}